server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pet-data
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          '[format_sql]': true

  graphql:
    graphql:
      enabled: true